# Generated by Django 3.0.7 on 2020-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='book_int',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='book_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
