# Generated by Django 3.0.7 on 2020-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0002_auto_20200919_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_label',
            field=models.IntegerField(blank=True, choices=[(0, '小説'), (1, '漫画'), (2, 'ビジネス書'), (3, '学習書'), (4, '教養書'), (5, '自己啓発本'), (6, 'その他')], null=True),
        ),
    ]
