# Generated by Django 3.0.7 on 2020-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0004_auto_20200927_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], default=1),
        ),
    ]
